[package]
name = "laz-rs-c"
version = "0.1.0"
authors = ["tmontaigu <thomas.montaigu@laposte.net>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.8.0"

[dependencies]
laz = { version = "0.6.0-alpha.1", features = ["parallel"] }
libc = "^0.2.86"
